#!/bin/bash
git clone https://github.com/milesgwood/milesgwood.github.io.git && \
git clone https://github.com/pages-themes/midnight && \
cd midnight && \
script/bootstrap && \
echo "Changing directory to milesgwood.github.io" && \
cd ../milesgwood.github.io/ && \
cp -n -R ../midnight . && \
echo "Copying gem 'github-pages', group: :jekyll_plugins to Gemfile"
echo "gem 'github-pages', group: :jekyll_plugins" >> Gemfile
python -mwebbrowser http://localhost:4000 && \
bundle exec jekyll serve
